#ifndef OZAYN_AUDIT_H
#define OZAYN_AUDIT_H

#include "identity.h"
#include "authentication.h"
#include "session_management.h"
#include "authorization.h"
#include "rbac.h"
#include "permission.h"
#include "mfa.h"
#include <stdint.h>
#include <stddef.h>
#include <time.h>

/*
 * audit.h — Security Audit & Security Event Logging Foundation (Step 21).
 *
 * Establishes a structured, tamper-aware, security-focused audit system
 * capable of recording security events generated by Steps 01-20.
 *
 * Architecture:
 *   SECURITY COMPONENT
 *          |
 *          v
 *   AUDIT SERVICE  <-- this layer
 *          |
 *          v
 *   EVENT VALIDATION
 *          |
 *          v
 *   AUDIT RECORD (ring buffer / storage)
 *          |
 *          v
 *   SECURE STORAGE
 *
 * The audit system OBSERVES and RECORDS security operations.
 * It does NOT decide whether an operation is allowed.
 *
 * Step 21 scope:
 *   - Structured security event model
 *   - Event type enumeration (identity, auth, password, attempt, MFA,
 *     session, authorization, RBAC, permission, security/system)
 *   - Event severity model
 *   - Event outcome model
 *   - Event validation (secret rejection, field validation)
 *   - In-memory ring buffer persistence
 *   - Storage abstraction interface
 *   - Controlled audit query with limits
 *   - Audit policy (severity thresholds, retention, required events)
 *   - Secret-safe auditing (password, key, token, biometric rejection)
 *   - Resource limits (max event size, metadata size, query limits)
 *   - Append-only security model
 *   - Integration points for all security subsystems
 *   - Concurrency-safe event recording
 *
 * NOT in scope:
 *   - GUI audit dashboard
 *   - SIEM integration
 *   - Remote centralized logging
 *   - Cloud audit service
 *   - Blockchain / hash-chain integrity
 *   - Security analytics / ML
 *   - Automatic incident response
 *   - External identity providers
 *   - Forensic platform
 */

/* ============================================================
 * SECTION 1 — ERROR / RESULT CODES
 * ============================================================ */

typedef enum {
    OZAYN_AUDIT_OK                     = 0,
    OZAYN_AUDIT_ERR                    = -1,
    OZAYN_AUDIT_ERR_NULL               = -2,
    OZAYN_AUDIT_ERR_NOT_INITIALIZED    = -3,
    OZAYN_AUDIT_ERR_ALREADY_INITIALIZED = -4,
    OZAYN_AUDIT_ERR_INVALID_EVENT      = -5,
    OZAYN_AUDIT_ERR_INVALID_TYPE       = -6,
    OZAYN_AUDIT_ERR_INVALID_OUTCOME    = -7,
    OZAYN_AUDIT_ERR_INVALID_SEVERITY   = -8,
    OZAYN_AUDIT_ERR_INVALID_TIMESTAMP  = -9,
    OZAYN_AUDIT_ERR_INVALID_IDENTITY   = -10,
    OZAYN_AUDIT_ERR_INVALID_SCOPE      = -11,
    OZAYN_AUDIT_ERR_INVALID_COMPONENT  = -12,
    OZAYN_AUDIT_ERR_METADATA_TOO_LARGE = -13,
    OZAYN_AUDIT_ERR_EVENT_TOO_LARGE    = -14,
    OZAYN_AUDIT_ERR_SECRET_REJECTED    = -15,
    OZAYN_AUDIT_ERR_STORAGE_FULL       = -16,
    OZAYN_AUDIT_ERR_STORAGE_ERROR      = -17,
    OZAYN_AUDIT_ERR_STORAGE_UNAVAILABLE = -18,
    OZAYN_AUDIT_ERR_EVENT_NOT_FOUND    = -19,
    OZAYN_AUDIT_ERR_QUERY_FAILED       = -20,
    OZAYN_AUDIT_ERR_POLICY_REJECTED    = -21,
    OZAYN_AUDIT_ERR_UNAVAILABLE        = -22,
    OZAYN_AUDIT_ERR_INTEGRITY_FAILURE  = -23,
    OZAYN_AUDIT_ERR_RESOURCE_EXHAUSTED = -24,
    OZAYN_AUDIT_ERR_WRITE_FAILED       = -25,
    OZAYN_AUDIT_ERR_READ_FAILED        = -26,
    OZAYN_AUDIT_ERR_REQUIRES_AUTH      = -27,
    OZAYN_AUDIT_ERR_ACCESS_DENIED      = -28,
} ozayn_audit_result_t;

/* ============================================================
 * SECTION 2 — EVENT TYPES
 * ============================================================ */

typedef enum {
    /* Identity events */
    OZAYN_AUDIT_IDENTITY_CREATED       = 0,
    OZAYN_AUDIT_IDENTITY_UPDATED       = 1,
    OZAYN_AUDIT_IDENTITY_SUSPENDED     = 2,
    OZAYN_AUDIT_IDENTITY_REVOKED       = 3,
    OZAYN_AUDIT_IDENTITY_ARCHIVED      = 4,

    /* Authentication events */
    OZAYN_AUDIT_AUTH_STARTED           = 10,
    OZAYN_AUDIT_AUTH_SUCCEEDED         = 11,
    OZAYN_AUDIT_AUTH_FAILED            = 12,
    OZAYN_AUDIT_AUTH_REJECTED          = 13,
    OZAYN_AUDIT_AUTH_UNAVAILABLE       = 14,

    /* Password authentication events */
    OZAYN_AUDIT_PWD_AUTH_SUCCEEDED     = 20,
    OZAYN_AUDIT_PWD_AUTH_FAILED        = 21,
    OZAYN_AUDIT_PWD_CREDENTIAL_CREATED = 22,
    OZAYN_AUDIT_PWD_CREDENTIAL_UPDATED = 23,
    OZAYN_AUDIT_PWD_CREDENTIAL_SUSPENDED = 24,
    OZAYN_AUDIT_PWD_CREDENTIAL_REVOKED = 25,

    /* Attempt protection events */
    OZAYN_AUDIT_RATE_LIMITED           = 30,
    OZAYN_AUDIT_TEMPORARILY_BLOCKED    = 31,
    OZAYN_AUDIT_ATTEMPT_RESET          = 32,

    /* MFA events */
    OZAYN_AUDIT_MFA_STARTED            = 40,
    OZAYN_AUDIT_MFA_FACTOR_VERIFIED    = 41,
    OZAYN_AUDIT_MFA_FACTOR_FAILED      = 42,
    OZAYN_AUDIT_MFA_COMPLETED          = 43,
    OZAYN_AUDIT_MFA_FAILED             = 44,
    OZAYN_AUDIT_MFA_EXPIRED            = 45,
    OZAYN_AUDIT_MFA_CANCELLED          = 46,
    OZAYN_AUDIT_MFA_BLOCKED            = 47,

    /* Session events */
    OZAYN_AUDIT_SESSION_CREATED        = 50,
    OZAYN_AUDIT_SESSION_VALIDATED      = 51,
    OZAYN_AUDIT_SESSION_EXPIRED        = 52,
    OZAYN_AUDIT_SESSION_TERMINATED     = 53,
    OZAYN_AUDIT_SESSION_REVOKED        = 54,

    /* Authorization events */
    OZAYN_AUDIT_AUTHZ_ALLOWED          = 60,
    OZAYN_AUDIT_AUTHZ_DENIED           = 61,
    OZAYN_AUDIT_AUTHZ_ERROR            = 62,

    /* RBAC events */
    OZAYN_AUDIT_ROLE_CREATED           = 70,
    OZAYN_AUDIT_ROLE_UPDATED           = 71,
    OZAYN_AUDIT_ROLE_SUSPENDED         = 72,
    OZAYN_AUDIT_ROLE_REVOKED           = 73,
    OZAYN_AUDIT_ROLE_ASSIGNED          = 74,
    OZAYN_AUDIT_ROLE_ASSIGNMENT_REVOKED = 75,
    OZAYN_AUDIT_ROLE_PERM_ADDED        = 76,
    OZAYN_AUDIT_ROLE_PERM_REMOVED      = 77,

    /* Permission events */
    OZAYN_AUDIT_PERM_CREATED           = 80,
    OZAYN_AUDIT_PERM_UPDATED           = 81,
    OZAYN_AUDIT_PERM_SUSPENDED         = 82,
    OZAYN_AUDIT_PERM_REVOKED           = 83,
    OZAYN_AUDIT_PERM_MATCHED           = 84,
    OZAYN_AUDIT_PERM_DENIED            = 85,

    /* Security / system events */
    OZAYN_AUDIT_POLICY_REJECTED        = 90,
    OZAYN_AUDIT_CONFIG_CHANGED         = 91,
    OZAYN_AUDIT_COMPONENT_UNAVAILABLE  = 92,
    OZAYN_AUDIT_INTEGRITY_FAILURE      = 93,
    OZAYN_AUDIT_STORAGE_FAILURE        = 94,
    OZAYN_AUDIT_VIOLATION_DETECTED     = 95,
    OZAYN_AUDIT_SERVICE_UNAVAILABLE    = 96,

    OZAYN_AUDIT_EVENT_TYPE_COUNT       = 97,
} ozayn_audit_event_type_t;

/* ============================================================
 * SECTION 3 — EVENT CATEGORIES
 * ============================================================ */

typedef enum {
    OZAYN_AUDIT_CAT_IDENTITY     = 0,
    OZAYN_AUDIT_CAT_AUTH         = 1,
    OZAYN_AUDIT_CAT_PASSWORD     = 2,
    OZAYN_AUDIT_CAT_ATTEMPT      = 3,
    OZAYN_AUDIT_CAT_MFA          = 4,
    OZAYN_AUDIT_CAT_SESSION      = 5,
    OZAYN_AUDIT_CAT_AUTHZ        = 6,
    OZAYN_AUDIT_CAT_RBAC         = 7,
    OZAYN_AUDIT_CAT_PERMISSION   = 8,
    OZAYN_AUDIT_CAT_SECURITY     = 9,
    OZAYN_AUDIT_CAT_AUDIT        = 10,

    OZAYN_AUDIT_CATEGORY_COUNT   = 11,
} ozayn_audit_category_t;

/* ============================================================
 * SECTION 4 — EVENT OUTCOME
 * ============================================================ */

typedef enum {
    OZAYN_AUDIT_OUTCOME_SUCCESS    = 0,
    OZAYN_AUDIT_OUTCOME_FAILURE    = 1,
    OZAYN_AUDIT_OUTCOME_DENIED     = 2,
    OZAYN_AUDIT_OUTCOME_REJECTED   = 3,
    OZAYN_AUDIT_OUTCOME_UNAVAILABLE = 4,
    OZAYN_AUDIT_OUTCOME_ERROR      = 5,
    OZAYN_AUDIT_OUTCOME_INFO       = 6,

    OZAYN_AUDIT_OUTCOME_COUNT      = 7,
} ozayn_audit_outcome_t;

/* ============================================================
 * SECTION 5 — EVENT SEVERITY
 * ============================================================ */

typedef enum {
    OZAYN_AUDIT_SEV_INFO     = 0,
    OZAYN_AUDIT_SEV_NOTICE   = 1,
    OZAYN_AUDIT_SEV_WARNING  = 2,
    OZAYN_AUDIT_SEV_HIGH     = 3,
    OZAYN_AUDIT_SEV_CRITICAL = 4,

    OZAYN_AUDIT_SEV_COUNT    = 5,
} ozayn_audit_severity_t;

/* ============================================================
 * SECTION 6 — AUDIT EVENT (core record)
 * ============================================================ */

#define OZAYN_AUDIT_MAX_SOURCE_LEN     64
#define OZAYN_AUDIT_MAX_ACTION_LEN     64
#define OZAYN_AUDIT_MAX_DETAIL_LEN     256
#define OZAYN_AUDIT_MAX_FAILURE_LEN    256
#define OZAYN_AUDIT_MAX_REQUEST_ID_LEN 64
#define OZAYN_AUDIT_MAX_CORR_ID_LEN    64
#define OZAYN_AUDIT_MAX_ID_LEN         64
#define OZAYN_AUDIT_MAX_RESOURCE_ID_LEN 64
#define OZAYN_AUDIT_MAX_METADATA_SIZE  512
#define OZAYN_AUDIT_MAX_EVENT_SIZE     2048

typedef struct {
    /* Core identification */
    char                        event_id[OZAYN_AUDIT_MAX_ID_LEN];
    ozayn_audit_event_type_t    event_type;
    uint32_t                    event_version;
    time_t                      timestamp;

    /* Outcome and severity */
    ozayn_audit_outcome_t       outcome;
    ozayn_audit_severity_t      severity;
    ozayn_audit_category_t      category;

    /* Security context — who and what */
    char                        identity_id[OZAYN_AUDIT_MAX_ID_LEN];
    char                        session_id[OZAYN_AUDIT_MAX_ID_LEN];
    ozayn_authn_method_t        auth_method;
    ozayn_mfa_assurance_t       assurance_level;

    /* Resource reference */
    ozayn_authz_resource_type_t resource_type;
    char                        resource_id[OZAYN_AUDIT_MAX_RESOURCE_ID_LEN];
    ozayn_authz_action_type_t   action;
    ozayn_authz_scope_t         scope;

    /* Source and correlation */
    char                        source_component[OZAYN_AUDIT_MAX_SOURCE_LEN];
    char                        request_id[OZAYN_AUDIT_MAX_REQUEST_ID_LEN];
    char                        correlation_id[OZAYN_AUDIT_MAX_CORR_ID_LEN];

    /* Detail */
    char                        detail[OZAYN_AUDIT_MAX_DETAIL_LEN];
    char                        failure_reason[OZAYN_AUDIT_MAX_FAILURE_LEN];

    /* Metadata — explicitly sanitized, bounded */
    uint8_t                     metadata[OZAYN_AUDIT_MAX_METADATA_SIZE];
    uint32_t                    metadata_size;
    int                         metadata_valid;
} ozayn_audit_event_t;

/* ============================================================
 * SECTION 7 — STORAGE ABSTRACTION
 * ============================================================ */

typedef struct {
    ozayn_audit_result_t (*append)(void *impl, const ozayn_audit_event_t *event);
    ozayn_audit_result_t (*get)(void *impl, const char *event_id, ozayn_audit_event_t *out);
    ozayn_audit_result_t (*count)(void *impl, int *out_count);
    void                 (*shutdown)(void *impl);
} ozayn_audit_storage_ops_t;

typedef struct {
    const char                  *name;
    const ozayn_audit_storage_ops_t *ops;
    void                        *impl;
    int                          initialized;
} ozayn_audit_storage_t;

/* ============================================================
 * SECTION 8 — AUDIT QUERY
 * ============================================================ */

#define OZAYN_AUDIT_QUERY_MAX_RESULTS 256

typedef struct {
    ozayn_audit_event_type_t  filter_type;
    int                       filter_type_active;

    char                      filter_identity_id[OZAYN_AUDIT_MAX_ID_LEN];
    int                       filter_identity_active;

    char                      filter_session_id[OZAYN_AUDIT_MAX_ID_LEN];
    int                       filter_session_active;

    ozayn_audit_outcome_t     filter_outcome;
    int                       filter_outcome_active;

    ozayn_audit_severity_t    filter_severity_min;
    int                       filter_severity_active;

    char                      filter_correlation_id[OZAYN_AUDIT_MAX_CORR_ID_LEN];
    int                       filter_correlation_active;

    char                      filter_source[OZAYN_AUDIT_MAX_SOURCE_LEN];
    int                       filter_source_active;

    time_t                    filter_time_from;
    time_t                    filter_time_to;
    int                       filter_time_active;

    int                       result_limit;
    int                       result_offset;
} ozayn_audit_query_t;

/* ============================================================
 * SECTION 9 — AUDIT POLICY
 * ============================================================ */

typedef struct {
    int                       enabled;
    ozayn_audit_severity_t    minimum_severity;
    int                       retention_events;
    int                       retention_seconds;
    int                       required_categories[OZAYN_AUDIT_CATEGORY_COUNT];
    int                       metadata_allowed;
    int                       require_identity;
    int                       max_event_size;
    int                       max_metadata_size;
} ozayn_audit_policy_t;

/* ============================================================
 * SECTION 10 — EVENT VERSION
 * ============================================================ */

#define OZAYN_AUDIT_EVENT_VERSION 1

/* ============================================================
 * SECTION 11 — AUDIT SERVICE
 * ============================================================ */

typedef struct {
    int                       initialized;
    ozayn_audit_policy_t      policy;

    /* In-memory ring buffer */
    ozayn_audit_event_t      *events;
    int                       event_capacity;
    int                       event_head;
    int                       event_count;
    uint64_t                  event_counter;

    /* Storage binding */
    ozayn_audit_storage_t    *storage;

    /* Stats */
    uint64_t                  total_events_recorded;
    uint64_t                  total_events_rejected;
    uint64_t                  total_secrets_rejected;
    uint64_t                  total_query_count;
} ozayn_audit_service_t;

/* ============================================================
 * SECTION 12 — SERVICE CONFIGURATION
 * ============================================================ */

typedef struct {
    int                       event_capacity;
    int                       max_event_size;
    int                       max_metadata_size;
    int                       default_retention_events;
    int                       default_retention_seconds;
    ozayn_audit_severity_t    default_minimum_severity;
    int                       require_identity;
} ozayn_audit_service_config_t;

/* ============================================================
 * SECTION 13 — LIFECYCLE
 * ============================================================ */

ozayn_audit_result_t ozayn_audit_service_init(ozayn_audit_service_t *svc,
                                               const ozayn_audit_service_config_t *cfg);
void                 ozayn_audit_service_shutdown(ozayn_audit_service_t *svc);
int                  ozayn_audit_service_is_initialized(const ozayn_audit_service_t *svc);

/* ============================================================
 * SECTION 14 — EVENT RECORDING
 * ============================================================ */

ozayn_audit_result_t ozayn_audit_record(ozayn_audit_service_t *svc,
                                         ozayn_audit_event_t *event);

/* ============================================================
 * SECTION 15 — EVENT QUERY
 * ============================================================ */

ozayn_audit_result_t ozayn_audit_query(const ozayn_audit_service_t *svc,
                                        const ozayn_audit_query_t *query,
                                        ozayn_audit_event_t *results,
                                        int max_results,
                                        int *out_count);

ozayn_audit_result_t ozayn_audit_get_by_id(const ozayn_audit_service_t *svc,
                                            const char *event_id,
                                            ozayn_audit_event_t *out);

int                  ozayn_audit_count(const ozayn_audit_service_t *svc);

/* ============================================================
 * SECTION 16 — STORAGE BINDING
 * ============================================================ */

ozayn_audit_result_t ozayn_audit_set_storage(ozayn_audit_service_t *svc,
                                              ozayn_audit_storage_t *storage);

/* ============================================================
 * SECTION 17 — POLICY
 * ============================================================ */

ozayn_audit_result_t ozayn_audit_set_policy(ozayn_audit_service_t *svc,
                                             const ozayn_audit_policy_t *policy);

const ozayn_audit_policy_t *ozayn_audit_get_policy(const ozayn_audit_service_t *svc);

/* ============================================================
 * SECTION 18 — EVENT VALIDATION
 * ============================================================ */

ozayn_audit_result_t ozayn_audit_validate_event(const ozayn_audit_service_t *svc,
                                                 const ozayn_audit_event_t *event);

/* ============================================================
 * SECTION 19 — SECRET FILTERING
 * ============================================================ */

ozayn_audit_result_t ozayn_audit_check_metadata_safe(const uint8_t *data,
                                                      uint32_t size);

/* ============================================================
 * SECTION 20 — EVENT BUILDER HELPERS
 * ============================================================ */

void ozayn_audit_event_init(ozayn_audit_event_t *event);

ozayn_audit_result_t ozayn_audit_event_set_type(ozayn_audit_event_t *event,
                                                 ozayn_audit_event_type_t type);

ozayn_audit_result_t ozayn_audit_event_set_outcome(ozayn_audit_event_t *event,
                                                    ozayn_audit_outcome_t outcome);

ozayn_audit_result_t ozayn_audit_event_set_severity(ozayn_audit_event_t *event,
                                                     ozayn_audit_severity_t sev);

ozayn_audit_result_t ozayn_audit_event_set_identity(ozayn_audit_event_t *event,
                                                     const char *identity_id);

ozayn_audit_result_t ozayn_audit_event_set_session(ozayn_audit_event_t *event,
                                                    const char *session_id);

ozayn_audit_result_t ozayn_audit_event_set_source(ozayn_audit_event_t *event,
                                                   const char *source);

ozayn_audit_result_t ozayn_audit_event_set_request_id(ozayn_audit_event_t *event,
                                                       const char *request_id);

ozayn_audit_result_t ozayn_audit_event_set_correlation_id(ozayn_audit_event_t *event,
                                                           const char *correlation_id);

ozayn_audit_result_t ozayn_audit_event_set_resource(ozayn_audit_event_t *event,
                                                     ozayn_authz_resource_type_t rtype,
                                                     const char *rid,
                                                     ozayn_authz_action_type_t action,
                                                     ozayn_authz_scope_t scope);

ozayn_audit_result_t ozayn_audit_event_set_detail(ozayn_audit_event_t *event,
                                                   const char *detail);

ozayn_audit_result_t ozayn_audit_event_set_failure_reason(ozayn_audit_event_t *event,
                                                           const char *reason);

ozayn_audit_result_t ozayn_audit_event_set_metadata(ozayn_audit_event_t *event,
                                                     const uint8_t *data,
                                                     uint32_t size);

/* ============================================================
 * SECTION 21 — NAME HELPERS
 * ============================================================ */

const char *ozayn_audit_result_name(ozayn_audit_result_t r);
const char *ozayn_audit_event_type_name(ozayn_audit_event_type_t t);
const char *ozayn_audit_category_name(ozayn_audit_category_t c);
const char *ozayn_audit_outcome_name(ozayn_audit_outcome_t o);
const char *ozayn_audit_severity_name(ozayn_audit_severity_t s);

/* ============================================================
 * SECTION 22 — TEST-ONLY STORAGE PROVIDER
 * ============================================================ */

typedef struct {
    ozayn_audit_event_t events[1024];
    int                 count;
    int                 fail_on_append;
    int                 unavailable;
    int                 corrupt_on_read;
    int                 initialized;
} ozayn_audit_test_storage_t;

void ozayn_audit_test_storage_init(ozayn_audit_test_storage_t *ts);
void ozayn_audit_test_storage_reset(ozayn_audit_test_storage_t *ts);
ozayn_audit_storage_t *ozayn_audit_test_storage_provider(ozayn_audit_test_storage_t *ts);

/* ============================================================
 * SECTION 23 — QH MANAGER (static global accessor)
 * ============================================================ */

ozayn_audit_service_t *ozayn_audit_get_global(void);

#endif
