#ifndef OZAYN_PASSWORD_AUTH_H
#define OZAYN_PASSWORD_AUTH_H

#include "authentication.h"
#include "identity.h"
#include "secure_vault.h"
#include <stdint.h>
#include <stddef.h>
#include <time.h>

/*
 * password_auth.h — Password Authentication & Credential Protection
 *                    (Section 03, Step 14).
 *
 * Implements password-based authentication for OZAYN identities.
 * Uses libsodium's Argon2id password hashing for secure credential
 * storage and verification. Passwords are never persisted in plaintext.
 *
 * Architecture:
 *   USER / APPLICATION
 *          |
 *          v
 *   AUTHENTICATION SERVICE
 *          |
 *          v
 *   PASSWORD AUTH PROVIDER  <-- this layer
 *          |
 *          v
 *   ARGON2id KDF (via libsodium)
 *          |
 *          v
 *   SECURE VAULT
 *          |
 *          v
 *   PROTECTED CREDENTIAL DATA
 *
 * Step 14 scope:
 *   - Password credential model (hash string only, no plaintext)
 *   - Secure password provisioning (generate salt, hash, store)
 *   - Password verification (Argon2id via crypto_pwhash_str_verify)
 *   - Unique cryptographic salts (generated by libsodium)
 *   - Password policy boundary (min/max length, configurable)
 *   - Credential lifecycle (ACTIVE, SUSPENDED, REVOKED, EXPIRED)
 *   - Secure Vault integration for credential persistence
 *   - Identity state checks (reject non-ACTIVE identities)
 *   - Fail-closed behavior on vault/provider failures
 *   - Sensitive memory handling (wipe password buffers)
 *   - Provider implementing ozayn_authn_provider_ops_t
 *
 * NOT in scope:
 *   - Password recovery / reset
 *   - MFA / multi-factor
 *   - Face / voice / gesture / biometric authentication
 *   - Session management
 *   - Authorization / RBAC
 *   - Login GUI
 *   - Account recovery
 *   - Email-based reset
 *   - Rate limiting / account lockout
 */

/* ============================================================
 * PASSWORD CREDENTIAL CONSTANTS
 * ============================================================ */

#define OZAYN_PWD_MAX_CREDENTIALS      64
#define OZAYN_PWD_MAX_ID_LEN           64
#define OZAYN_PWD_MAX_IDENTITY_ID_LEN  64
#define OZAYN_PWD_HASH_STR_LEN        128  /* crypto_pwhash_STRBYTES */

/* ============================================================
 * PASSWORD CREDENTIAL STATE
 * ============================================================ */

typedef enum {
    OZAYN_PWD_CRED_UNINITIALIZED = 0,
    OZAYN_PWD_CRED_ACTIVE        = 1,
    OZAYN_PWD_CRED_SUSPENDED     = 2,
    OZAYN_PWD_CRED_REVOKED       = 3,
    OZAYN_PWD_CRED_EXPIRED       = 4
} ozayn_pwd_credential_state_t;

/* ============================================================
 * PASSWORD CREDENTIAL OBJECT
 *
 * Contains only the password hash string (Argon2id encoded).
 * The plaintext password is NEVER stored or retained.
 * ============================================================ */

typedef struct {
    char                            id[OZAYN_PWD_MAX_ID_LEN];
    char                            identity_id[OZAYN_PWD_MAX_IDENTITY_ID_LEN];
    char                            hash_str[OZAYN_PWD_HASH_STR_LEN];
    ozayn_pwd_credential_state_t    state;
    uint32_t                        version;
    time_t                          created_at;
    time_t                          modified_at;
    int                             in_use;
} ozayn_pwd_credential_t;

/* ============================================================
 * PASSWORD POLICY
 * ============================================================ */

typedef struct {
    int     min_length;       /* Minimum password length (default 8) */
    int     max_length;       /* Maximum password length (default 4096) */
    int     enabled;          /* 1 = policy active, 0 = policy disabled */
} ozayn_pwd_policy_t;

/* ============================================================
 * PASSWORD AUTH ERROR CODES
 * ============================================================ */

typedef enum {
    OZAYN_PWD_OK                      =   0,
    OZAYN_PWD_ERR_NULL                =  -1,
    OZAYN_PWD_ERR_NOT_INITIALIZED     =  -2,
    OZAYN_PWD_ERR_NOT_FOUND           =  -3,
    OZAYN_PWD_ERR_INVALID             =  -4,
    OZAYN_PWD_ERR_EMPTY_PASSWORD      =  -5,
    OZAYN_PWD_ERR_PASSWORD_TOO_SHORT  =  -6,
    OZAYN_PWD_ERR_PASSWORD_TOO_LONG   =  -7,
    OZAYN_PWD_ERR_KDF_FAILED          =  -8,
    OZAYN_PWD_ERR_VERIFICATION_FAILED =  -9,
    OZAYN_PWD_ERR_CREDENTIAL_REVOKED  = -10,
    OZAYN_PWD_ERR_CREDENTIAL_SUSPENDED= -11,
    OZAYN_PWD_ERR_CREDENTIAL_EXPIRED  = -12,
    OZAYN_PWD_ERR_VAULT_FAILED        = -13,
    OZAYN_PWD_ERR_STORAGE_FAILED      = -14,
    OZAYN_PWD_ERR_ALREADY_EXISTS      = -15,
    OZAYN_PWD_ERR_IDENTITY_REVOKED    = -16,
    OZAYN_PWD_ERR_IDENTITY_SUSPENDED  = -17,
    OZAYN_PWD_ERR_IDENTITY_ARCHIVED   = -18
} ozayn_pwd_error_t;

/* ============================================================
 * PASSWORD PROVISIONING REQUEST
 * ============================================================ */

typedef struct {
    char    identity_id[OZAYN_PWD_MAX_IDENTITY_ID_LEN];
    char    password[4096];  /* Temporary plaintext — wiped after use */
    size_t  password_len;
} ozayn_pwd_provision_request_t;

/* ============================================================
 * PASSWORD VERIFICATION REQUEST
 * ============================================================ */

typedef struct {
    char    identity_id[OZAYN_PWD_MAX_IDENTITY_ID_LEN];
    char    password[4096];  /* Temporary plaintext — wiped after use */
    size_t  password_len;
} ozayn_pwd_verify_request_t;

/* ============================================================
 * PASSWORD AUTH SERVICE CONFIGURATION
 * ============================================================ */

typedef struct {
    ozayn_identity_service_t    *identity_service;
    ozayn_vault_t               *vault;
    ozayn_pwd_policy_t           policy;
} ozayn_pwd_service_config_t;

/* ============================================================
 * PASSWORD AUTH SERVICE
 * ============================================================ */

typedef struct {
    ozayn_pwd_credential_t       credentials[OZAYN_PWD_MAX_CREDENTIALS];
    int                          credential_count;
    ozayn_pwd_service_config_t   config;
    int                          initialized;
} ozayn_pwd_service_t;

/* ============================================================
 * SERVICE LIFECYCLE
 * ============================================================ */

ozayn_pwd_error_t ozayn_pwd_service_init(ozayn_pwd_service_t *svc,
                                          const ozayn_pwd_service_config_t *config);

void ozayn_pwd_service_shutdown(ozayn_pwd_service_t *svc);

/* ============================================================
 * PASSWORD PROVISIONING
 * Create a new password credential for an identity.
 * The plaintext password is hashed with Argon2id and stored
 * in the Secure Vault. Plaintext is never persisted.
 * ============================================================ */

ozayn_pwd_error_t ozayn_pwd_provision(ozayn_pwd_service_t *svc,
                                       const ozayn_pwd_provision_request_t *request,
                                       ozayn_authn_credential_ref_t *out_ref);

/* ============================================================
 * PASSWORD VERIFICATION
 * Verify a plaintext password against a stored credential.
 * Returns verification result without exposing the hash.
 * ============================================================ */

ozayn_pwd_error_t ozayn_pwd_verify(ozayn_pwd_service_t *svc,
                                    const ozayn_pwd_verify_request_t *request,
                                    ozayn_authn_result_t *out_result);

/* ============================================================
 * PASSWORD UPDATE
 * Replace an existing password credential.
 * Old credential remains active until new one is confirmed stored.
 * ============================================================ */

ozayn_pwd_error_t ozayn_pwd_update(ozayn_pwd_service_t *svc,
                                    const char *identity_id,
                                    const char *new_password,
                                    size_t new_password_len);

/* ============================================================
 * CREDENTIAL STATE MANAGEMENT
 * ============================================================ */

ozayn_pwd_error_t ozayn_pwd_suspend(ozayn_pwd_service_t *svc,
                                     const char *identity_id);

ozayn_pwd_error_t ozayn_pwd_revoke(ozayn_pwd_service_t *svc,
                                    const char *identity_id);

/* ============================================================
 * QUERY
 * ============================================================ */

int ozayn_pwd_service_is_initialized(const ozayn_pwd_service_t *svc);
int ozayn_pwd_service_credential_count(const ozayn_pwd_service_t *svc);
int ozayn_pwd_has_credential(const ozayn_pwd_service_t *svc,
                              const char *identity_id);

/* ============================================================
 * VALIDATION
 * ============================================================ */

int ozayn_pwd_validate_credential_state(ozayn_pwd_credential_state_t state);
int ozayn_pwd_validate_credential_transition(ozayn_pwd_credential_state_t from,
                                              ozayn_pwd_credential_state_t to);
int ozayn_pwd_validate_password(const ozayn_pwd_service_t *svc,
                                 const char *password,
                                 size_t password_len);

/* ============================================================
 * NAME HELPERS
 * ============================================================ */

const char *ozayn_pwd_credential_state_name(ozayn_pwd_credential_state_t state);
const char *ozayn_pwd_error_name(ozayn_pwd_error_t error);

/* ============================================================
 * TEST SUPPORT
 * Create a password auth provider that implements
 * ozayn_authn_provider_ops_t for use with the auth service.
 * ============================================================ */

void ozayn_pwd_provider_create(ozayn_authn_provider_t *provider,
                                ozayn_pwd_service_t *pwd_svc);

#endif
